
[experience]
	#Sets the maximum level cap for weapons and armor. Default: 10
	maxLevel = 20
	#The experience amount needed for the first level(1). Default: 100
	level1Experience = 200
	#The experience multiplier for each level based on the first level experience. Default: 1.8
	experienceMultiplier = 2.0

[miscellaneous]
	#Determines whether or not durability will be displayed in tooltips. Default: true
	showDurabilityInTooltip = false
	#Determines if the vanilla items won't be affected by this mod. Default: false
	onlyModdedItems = false
	#Items in this blacklist will not gain the leveling systems. Useful for very powerful items or potential conflicts. Style should be 'modid:item'
	itemBlacklist = []
	#This is an extra item list to add custom support for such modded items. Be careful on this, it may crash if the item can't be enhanced. Style should be 'modid:item'
	extraItems = []
	#This is item whitelist, basically. If you don't want a whitelist, just leave this empty. If you want a whitelist, fill it with items you want. Style should be 'modid:item'
	itemWhitelist = []

[abilities]
	#Determines whether or not the specific ability will be present in-game. Default: true
	adrenalineAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	illuminationAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	bombasticAbility = false
	#Determines whether or not the specific ability will be present in-game. Default: true
	criticalpointAbility = false
	#Determines whether or not the specific ability will be present in-game. Default: true
	hardenedAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	etherealAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	moltenAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	fireAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	remedialAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	frostAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	innateAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	frozenAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	bloodthirstAbility = false
	#Determines whether or not the specific ability will be present in-game. Default: true
	toxicAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	beastialAbility = true
	#Determines whether or not the specific ability will be present in-game. Default: true
	poisonAbility = true

[abilitychances]
	#Determines how rare the Molten ability will occur. (Higher values=lower occurance) Default: 4
	moltenchance = 10.0
	#Determines how rare the Toxic ability will occur. (Higher values=lower occurance) Default: 4
	toxicchance = 10.0
	#Determines how rare the Adrinalin ability will occur. (Higher values=lower occurance) Default: 4
	adrenalinechance = 20.0
	#Determines how rare the Frost ability will occur. (Higher values=lower occurance) Default: 4
	frostchance = 16.0
	#Determines how rare the Harden ability will occur. (Higher values=lower occurance) Default: 4
	hardenedchance = 20.0
	#Determines how rare the Bombasitc ability will occur. (Higher values=lower occurance) Default: 4
	bombasticchance = 24.0
	#Determines how rare the Critical Point ability will occur. (Higher values=lower occurance) Default: 4
	criticalpointchance = 20.0
	#Determines how rare the Poison ability will occur. (Higher values=lower occurance) Default: 4
	poisonchance = 10.0
	#Determines how rare the Frozen ability will occur. (Higher values=lower occurance) Default: 4
	frozenchance = 10.0
	#Determines how rare the Fire ability will occur. (Higher values=lower occurance) Default: 4
	firechance = 10.0
	#Determines how rare the Innate ability will occur. (Higher values=lower occurance) Default: 4
	innatechance = 10.0

[rarities]
	#Sets the chance the given rarity will be applied. Default: 0.18
	uncommonChance = 0.2
	#Sets the chance the given rarity will be applied. Default: 0.05
	ultraRareChance = 0.04
	#Sets the chance the given rarity will be applied. Default: 0.02
	legendaryChance = 0.02
	#Sets the chance the given rarity will be applied. Default: 0.5
	basicChance = 0.6
	#Sets the chance the given rarity will be applied. Default: 0.1
	rareChance = 0.08
	#Sets the chance the given rarity will be applied. Default: 0.01
	archaicChance = 0.01

[multiplier]
	#Sets the effectiveness for the given rarity. Default: 0.305
	rareDamage = 2.088
	#Sets the effectiveness for the given rarity. Default: 0.155
	uncommonDamage = 1.848
	#Sets the effectiveness for the given rarity. Default: 0.38
	ultraRareDamage = 2.208
	#Sets the effectiveness for the given rarity. Default: 0.57
	legendaryDamage = 2.512
	#Sets the effectiveness for the given rarity. Default: 0
	basicDamage = 1.6
	#Sets the effectiveness for the given rarity. Default: 0.81
	archaicDamage = 2.896

