
#Config options for the Hunter and Variants.
[Hunter]
	#Spawn weight for the Hunter. (Default: 90)
	#Range: 0 ~ 10000
	weight = 90
	#Minimum amount of hunters to spawn in a group. (Default: 1)
	min_group = 1
	#Maximum amount of hunters to spawn in a group. (Default: 3)
	max_group = 3
	#Drop chance in % for the "Hunter's Bow". (Default: 8)
	#Range: 0 ~ 100
	drop_chance = 8
	#Spawn Biomes/BiomeCategories where the Hunter will spawn.
	spawn_biomes = ["jungle"]

	#The Head Hunter is a special variant of the Hunter. It's even more deadly!
	[Hunter.Head_Hunter]
		#Enables the spawning of the Head Hunter. (Default: true)
		head_hunter = true
		#Spawn weight for the Head Hunter. (Default: 10)
		#Range: 0 ~ 10000
		weight = 10

		#This is the interval between shots.
		[Hunter.Head_Hunter.Firing_Speed]
			#Tweak the firing speed of the Head Hunter. (Default: 20)
			#For reference: The Vanilla Skeleton firing speed is: 40.
			firing_speed = 20
			#Tweak the firing speed of the Head Hunter for the Hard Difficulty. (Default: 10)
			#For reference: The Vanilla Skeleton firing speed for the Hard difficulty is: 20.
			firing_speed_hard = 10

[Debug]
	#Enables a logger for more info about the registered spawns. (Default: false)
	spawn_logger = false

	[Debug.mobs]
		#Gives Hunters the glowing effect. (Default: false)
		glowing_hunters = false
		#Gives Head Hunters the glowing effect. (Default: false)
		glowing_head_hunters = false

