storagenetwork = false
tconstruct = false
fastfurnaceminusreplacement = true
sophisticatedbackpacks = false
fastfurnace = false
craftingstation = true
ironfurnaces = true
occultism = false
jei = true
extendedcrafting = false
fastbenchminusreplacement = true
refinedstorageaddons = false
craftingcraft = false
toms_storage = true
refinedstorage = false
prettypipes = false
fastbench = false
cyclic = false
appliedenergistics2 = false

