
#No comment
[common]
	#Use single page mode
	useSinglePageMode = false
	#Stack size limit of slot
	#Range: 64 ~ 4294967295
	slotStackLimit = 4294967295
	#Maximum page limit
	#Range: 2 ~ 79536431
	maxPageLimit = 79536431
	#*Recovery options* Reset the max page that is 0.
	#Range: 1 ~ 79536431
	resetMaxPage = 1
	#Inventory rows for multi page mode
	#Range: 1 ~ 6
	inventoryRows = 3

