
#Spawning configuration settings
#All of these settings require a game restart to take effect
[spawns]
	#Range: 0 ~ 25
	clownfishWeight = 2
	#Mobs will only spawn in the biomes from the given mod IDs
	#You can see a mod's ID by clicking the 'Mods' button on the main screen and clicking on the mod's name on the left
	biomeWhitelist = ["minecraft", "projectvibrantjourneys", "environmental", "atmospheric", "autumnity", "bayou_blues"]
	#Range: 0 ~ 25
	maskedButterflyfishWeight = 2
	#Range: 0 ~ 25
	bannerfishWeight = 2
	#Range: 0 ~ 25
	butterflyfishWeight = 2
	#Range: 0 ~ 25
	raccoonButterflyfishWeight = 2
	#Range: 0 ~ 25
	seahorseWeight = 2
	#Range: 0 ~ 25
	swordfishWeight = 1
	#Range: 0 ~ 25
	fishWeight = 2
	#Range: 0 ~ 25
	blackcapBassletWeight = 2
	#Range: 0 ~ 25
	seaSerpentWeight = 1
	#Range: 0 ~ 25
	fairyBassletWeight = 2
	#Range: 0 ~ 25
	spotfinButterflyfishWeight = 2
	#Range: 0 ~ 25
	sailfishWeight = 1

