"Allow all items to be added" = false
"Whitelisted Items" = ["enigmaticlegacy:the_acknowledgment", "alexsmobs:animal_dictionary"]
"Whitelisted Names" = ["book", "tome", "lexicon", "nomicon", "manual", "knowledge", "pedia", "compendium", "guide", "codex", "journal"]
"Blacklisted Mods" = []
"Mod Aliases" = []

