
#General configuration settings
[General]
	#Use F3+H to show tooltips and get the name of the item, place it here. It get delete. Example: ["minecraft:stone"]
	#or if you need to ban multiple ["minecraft:stone", "minecraft:dirt"]
	"Items To Delete" = ["atum:wanderer_boots", "atum:wanderer_legs", "atum:wanderer_chest", "atum:wanderer_helmet", "minecraft:chainmail_helmet", "minecraft:chainmail_boots", "minecraft:chainmail_leggings", "minecraft:chainmail_chestplate", "gaiadimension:diopside_helmet", "easy_emerald:emerald_paxel", "easy_emerald:ruby_paxel", "easy_emerald:obsidian_paxel", "relics:infinity_ham", "quark:matrix_enchanter", "relics:rage_glove", "savageandravage:wand_of_freezing", "iceandfire:cyclops_eye", "mowziesmobs:ice_crystal", "artifacts:everlasting_beef", "gaiadimension:diopside_chestplate", "gaiadimension:diopside_legs", "gaiadimension:diopside_boots", "gaiadimension:diopside", "gaiadimension:diopside_block"]
	#Enables/Disables the constant removal of items.
	"Is it on?" = true

