
#Dynamic Lights Settings
[Settings]

	[Settings.Misc]
		"Cloud Height [Raw, Default 196]" = 256
		"Chunk Fade In Quality (OFF, FAST, FANCY)" = "FAST"
		"Render Fog" = false
		#Allowed Values: WINDOWED, BORDERLESS, FULLSCREEN
		"Use Borderless Fullscreen" = "WINDOWED"

	[Settings."FPS Counter"]
		"Display FPS Counter (OFF, SIMPLE, ADVANCED)" = "SIMPLE"
		"FPS Counter Distance" = 12

	[Settings."Entity Distance"]
		"Enable Max Distance Checks" = true
		"(TileEntity) Max Horizontal Render Distance [Squared, Default 64^2]" = 2304
		"(TileEntity) Max Vertical Render Distance [Raw, Default 32]" = 24
		"(Entity) Max Horizontal Render Distance [Squared, Default 64^2]" = 2304
		"(Entity) Max Vertical Render Distance [Raw, Default 32]" = 24

	[Settings.Zoom]
		"Lower Zoom Sensitivity" = true
		"Zoom Scrolling Enabled" = true
		"Zoom Transition Mode (OFF, LINEAR, SMOOTH)" = "SMOOTH"
		"Zoom Transition Mode (TOGGLE, HOLD, PERSISTENT)" = "HOLD"
		"Cinematic Camera Mode (OFF, VANILLA, MULTIPLIED)" = "OFF"
		"Zoom Overlay?" = false

