
[experience]
	#Make the player drop experience on death, 
	#make sure to disable this when using the keep option because of XP dupes
	dropExperience = true
	#Make the player keep experience when respawning
	keepExperience = false

[hunger]
	#Make the player keep hunger when respawning
	keepHunger = false
	#The lowest hunger value the player can have when respawning, must be used with keepHunger
	#Range: 0 ~ 20
	lowestHunger = 6

	[hunger.saturation]
		#Make the player keep saturation when respawning
		keepSaturation = false
		#Make the player keep saturation when respawning only when hunger is full. Only usable with the other two options
		keepSaturationWithFullHunger = true
		#The lowest saturation value the player can have when respawning, must be used with keepSaturation
		#Range: 0 ~ 20
		lowestSaturation = 6

	[hunger.no_appetite]
		#The duration that the player will have the 'No Appetite' effect after respawning (seconds)
		#Range: > 0
		effectDuration = 120

[health]
	#The amount of health to respawn with. Value is disabled if set to 0.
	#Range: 0 ~ 1024
	respawnHealth = 0
	#Enable all health modifications inside subcategories.
	enabled = false

	[health.values]
		#Lowest amount of health a player can have.
		#If set to 0, only maximal health is used.
		#Range: 0 ~ 1024
		minHealthAmount = 6
		#Starting health for a player.
		#Allowed Values: "MIN", "MAX" or just a number.
		startingHealthAmount = "MIN"
		#Highest amount of health a player can have.
		#Range: 1 ~ 1024
		maxHealthAmount = 20
		#Amount of health lost on each death.
		#Requires minimal health to be higher than 0.
		#Range: 0 ~ 1024
		deathDecreasedHealthAmount = 1

	[health.additional]
		#Values which, when reached, move the lowest health of the player to the achieved value.
		#Lowest threshold value can be non-removable, meaning that max health won't decrease on death until a player reaches maximal heath that is over the lowest threshold. To use it make the lowest value negative.Values must be in ascending order!
		healthThresholds = [-8, 16]
		#Config options which when changed should be considered for max health reset in an already created world.
		#Allowed Values: MIN_HEALTH, MAX_HEALTH, STARTING_HEALTH
		configChangeReset = ["MIN_HEALTH", "MAX_HEALTH", "STARTING_HEALTH"]
		#Condition for consumption of regenerative items. These values only apply on items without any use animations as to not consume them unintentionally.
		#Allowed Values: NOT_CROUCHING, CROUCHING, BOTH
		#Allowed Values: NOT_CROUCHING, CROUCHING, BOTH
		regenerativeItemsConsumptionMode = "NOT_CROUCHING"
		#Show a message when a threshold is reached and when health is gained or lost
		healthChangeMessage = true
		#Enables 'hardcore' mode which makes the player a spectator when 0 maximal health is reached.
		#Setting 'min_health' to 0 and removing all 'thresholds' is required or unexpected behaviour might happen.
		hardcoreMode = false
		#Items that increase or decrease current maximal health when used.
		#Format: "modid:item = N" with N being the health amount. Appending ':' after a negative N will make an item bypass thresholds.
		regenerativeItems = ["minecraft:nether_star = 1", "minecraft:enchanted_golden_apple = 1", "minecraft:dragon_egg = 1"]

