
#Ancient Classes Mod Configuration Settings
[general]
	#Enable this if you want to apply your branches configuration
	"Enable Custom Values" = false
	#Enable this if you want to disable the morph message when the player cant learn it.
	"Disable Morph Message" = true

#Item Related Configuration
[items]
	#Format 'Item{NBT}=Value', Value Unit = Half Soul
	"Soul Restore Items" = ["byg:nightshade_berries=4", "byg:crimson_berries=3", "create:chocolate_glazed_berries=3", "byg:blueberries=2", "byg:holly_berries=1", "minecraft:sweet_berries=1"]
	#Only drinkable or eatables can be appended by commas, the item format is the same as a give command
	"Forget Items" = ["enigmaticlegacy:unholy_grail"]

#Branches related configuration, All values must be > 0
[branches]

	[branches.stone_branch]

		[branches.stone_branch.boost_ability]
			maxCost = [8, 6, 4]
			maxCooldown = [280, 200, 140]
			maxDuration = [40, 60, 80]

		[branches.stone_branch.protect_ability]
			maxCost = [4, 4, 4]
			maxCooldown = [540, 380, 300]
			maxDuration = [100, 140, 200]
			maxCharges = [2, 3, 5]
			maxRange = [1, 3, 5]
			maxDamageReduction = [0.2, 0.4, 0.8]

		[branches.stone_branch.dash_ability]
			maxCost = [4, 4, 4]
			maxCooldown = [400, 360, 320]
			maxDuration = [20, 40, 60]
			maxVelocity = [1.0, 1.25, 1.5]

		[branches.stone_branch.cover_ability]
			maxCost = [10, 8, 6]
			maxCooldown = [3600, 1800, 900]
			maxDuration = [400, 400, 400]
			maxDomeRange = [2, 3, 4]
			maxBridgeRange = [8, 12, 20]

		[branches.stone_branch.stone_passive]
			maxCooldown = [1200, 900, 600]
			maxDuration = [60, 100, 140]

	[branches.diamond_branch]

		[branches.diamond_branch.condense_magic_ability]
			maxCost = [4, 3, 2]
			maxCooldown = [60, 40, 30]
			maxCast = [40, 30, 10]
			maxLife = [7, 8, 10]
			maxDiameter = [0.5, 0.5, 0.5]
			maxDamage = [6, 7, 9]
			maxVelocity = [1.0, 1.25, 1.5]

		[branches.diamond_branch.scatter_magic_ability]
			maxCost = [10, 8, 6]
			maxCooldown = [700, 600, 400]
			maxDuration = [60, 80, 140]
			maxLife = [20, 20, 20]
			maxDiameter = [3.0, 5.0, 7.0]
			maxDamage = [0.25, 0.5, 1.0]
			damageReduction = [0.15, 0.35, 0.5]
			bonusReduction = [0.08, 0.09, 0.1]

		[branches.diamond_branch.rouse_magic_ability]
			maxCost = [6, 6, 4]
			maxCooldown = [340, 300, 200]
			maxCast = [40, 30, 10]
			maxLife = [40, 60, 100]
			maxDiameter = [7.0, 8.0, 10.0]
			maxDamage = [0.5, 0.75, 1.0]

		[branches.diamond_branch.ancient_ritual_ability]
			maxCost = [8, 6, 4]
			maxCooldown = [500, 300, 200]
			maxDuration = [200, 300, 500]

		[branches.diamond_branch.diamond_passive]
			maxCooldown = [24000, 18000, 12000]

	[branches.bone_branch]

		[branches.bone_branch.leech_ability]
			maxCost = [6, 6, 4]
			maxCooldown = [600, 500, 300]
			maxDuration = [40, 60, 120]
			maxLifeSteal = [0.2, 0.4, 0.75]

		[branches.bone_branch.bargain_ability]
			maxCost = [6, 4, 2]
			maxCooldown = [40, 20, 10]
			maxDuration = [140, 140, 120]
			maxCast = [40, 30, 10]
			maxLife = [7, 8, 10]
			maxDiameter = [0.5, 0.5, 0.5]
			maxDamage = [1.0, 1.5, 3.0]
			maxVelocity = [0.6, 0.8, 1.25]
			maxCharges = [1, 2, 3]

		[branches.bone_branch.ghastling_ability]
			maxCost = [8, 6, 4]
			maxCooldown = [1000, 800, 600]
			maxDuration = [300, 400, 500]
			ghastlingBonus = [2, 4, 6]

		[branches.bone_branch.soulbound_ability]
			maxCost = [6, 4, 2]
			maxCooldown = [900, 600, 500]
			maxDuration = [200, 400, 500]
			maxCast = [20, 20, 20]
			maxLife = [20, 25, 30]
			maxDiameter = [0.5, 0.5, 0.5]
			maxVelocity = [1.0, 2.0, 3.0]
			graceHealth = [2, 4, 6]

		[branches.bone_branch.bone_passive]
			maxCooldown = [2400, 2100, 1500]
			maxDuration = [60, 80, 100]

	[branches.feather_branch]

		[branches.feather_branch.precise_shot_ability]
			maxCost = [6, 4, 2]
			maxCooldown = [320, 280, 200]
			maxDuration = [80, 80, 100]
			maxCharges = [2, 4, 6]
			maxVelocity = [0.4, 0.5, 0.7]

		[branches.feather_branch.agile_hands_ability]
			maxCost = [10, 8, 6]
			maxCooldown = [400, 300, 200]
			maxDuration = [40, 60, 80]
			maxRange = [1, 2, 4]

		[branches.feather_branch.slide_hook_ability]
			maxCost = [8, 6, 2]
			maxCooldown = [80, 60, 40]
			maxDuration = [300, 240, 200]
			maxCharges = [1, 2, 3]
			maxVelocity = [0.6, 0.75, 1.0]

		[branches.feather_branch.hunter_hints_ability]
			maxCost = [6, 4, 2]
			maxCooldown = [400, 360, 320]
			maxDuration = [100, 200, 400]
			minMobs = [1, 2, 3]

		[branches.feather_branch.feather_passive]
			maxCooldown = [1800, 1500, 900]
			maxDuration = [80, 100, 200]

	[branches.leaf_branch]

		[branches.leaf_branch.equilibrate_ability]
			maxCost = [8, 4, 2]
			maxCooldown = [400, 360, 320]
			maxCast = [40, 30, 10]
			maxLife = [9, 12, 15]
			maxDiameter = [0.5, 0.5, 0.5]
			maxVelocity = [0.35, 0.5, 0.7]
			flowerDuration = [1.5, 1.75, 2.5]

		[branches.leaf_branch.imitate_ability]

			[branches.leaf_branch.imitate_ability.player]
				maxCost = [8, 4, 2]
				maxCooldown = [900, 700, 500]
				maxCast = [40, 30, 10]
				maxLife = [20, 10, 5]
				maxDiameter = [4.0, 5.0, 6.0]
				flowerDuration = [1.0, 1.25, 1.5]
				morphEffectDuration = [100, 140, 180]

			[branches.leaf_branch.imitate_ability.overgrowth_ability]
				maxCost = [12, 10, 8]
				maxCooldown = [400, 360, 320]
				maxDuration = [40, 60, 100]
				maxRange = [3, 5, 8]

			[branches.leaf_branch.imitate_ability.morph_ability]
				maxCost = [12, 10, 8]
				maxCooldown = [400, 360, 320]
				maxDuration = [400, 600, 1000]

			[branches.leaf_branch.imitate_ability.leaf_passive]
				maxCooldown = [6000, 3600, 2400]
				maxDuration = [20, 20, 20]

